openthread-iwxxx-spi: Fix malformed Upstream Status
Fix malformed Upstream Status in patch 0001-ot-daemon-spi_interface-make-reset-device-and-line-o.patch.

Fixes:
ERROR: openthread-iwxxx-spi-1.0-r0 do_patch: QA Issue: Malformed Upstream-Status in patch
...
Please correct according to https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#patch-upstream-status

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>
(cherry picked from commit eebb7c6d67afadbbb577220185d1d434092aee0e)