layer.conf: add scarthgap to meta-nxp-connectivity LAYERSERIES_COMPAT
The meta-nxp-connectivity was updated to tag rel_imx_6.12.20_2.0.0. This
tag is not compatible with Yocto Scarthgap, resulting in the following
Yocto build error:

  ERROR: Layer nxp-matter-baseline is not compatible with the core layer
  which only supports these series: scarthgap (layer is compatible with
  styhead walnascar)

Append LAYERSERIES_COMPAT variables adding Scarthgap compatibility to
the relevant nxp-connectivity layers.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>